name: Quests
version: '${project.version}'
main: com.titanborn.plugin.Quests
api-version: 1.19
depend: [MMOCore]
authors: [Optivat, ArcaneBeast]
commands:
  quests:
    description: Quests for questing purposes.